// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
// deno-lint-ignore-file

import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "ar";

export type Locales =
  | "ar"
  | "en";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  /**
   * م​د​و​ن​ة​ ​ا​ل​غ​و​ل
   */
  TITLE: string;
};

export type TranslationFunctions = {
  /**
   * مدونة الغول
   */
  TITLE: () => LocalizedString;
};

export type Formatters = {};
